PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ruian: <http://ruian.linked.opendata.cz/ontology/>
PREFIX mfcr: <http://linked.opendata.cz/ontology/domain/mfcr/monitor/ciselniky/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX app: <http://linked.opendata.cz/ontology/mfcr/application/>

PREFIX resource: <{{"param": "resource"}}>

CONSTRUCT {
  resource: a mfcr:UcetniJednotka ;
    skos:prefLabel ?ujName ;
    mfcr:druhUcetniJednotky ?ujDruh;
    mfcr:poddruhUcetniJednotky ?ujPodDruh ;
	app:okres ?okres ;
    mfcr:adresa ?ujAdresa .

  ?ujDruh skos:prefLabel ?ujDruhLabel .

  ?ujPodDruh skos:prefLabel ?ujPodDruhLabel .
} WHERE {

  ?ujv a mfcr:UcetniJednotka ;
    mfcr:versionOf resource: ;
    mfcr:validTo ?ujValidTo ;
	mfcr:nuts/owl:sameAs/^ruian:lau ?okres;
    skos:prefLabel ?ujName ;
    mfcr:druhUcetniJednotky ?ujDruh;
    mfcr:poddruhUcetniJednotky ?ujPodDruh ;
    mfcr:adresa ?ujAdresa .

  ?ujDruh skos:prefLabel ?ujDruhLabel .

  ?ujPodDruh skos:prefLabel ?ujPodDruhLabel .

  FILTER (NOW() < ?ujValidTo)
}